Repository SatelliteQE/satellite6-upgrade, pull requests merged in 2018-04, with the labels that each got.

#163 Added foreman-debug and LogAnalyzer in foreman-maintain upgrade
  upgrade/helpers/tasks.py
Labels: Review

#165 Adds the latest base OS repo to capsules
  upgrade/capsule.py
  upgrade/helpers/tasks.py
Labels: Critical, Review, bug, enhancement

#166 Use foreman-maintain in upgrade pipeline
  upgrade/helpers/tasks.py
  upgrade/satellite.py
Labels: Blocker, Critical, High, Review

#167 whitelist check for 6.2 and 6.2.z upgrade
  upgrade/helpers/tasks.py
Labels: Review

#168 Disable foreman-maintain for 6.4
  upgrade/satellite.py
Labels: Review
